In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [19]:
df = pd.read_csv("/content/energydata_complete.csv")

In [11]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [12]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Appliances,19735.0,97.694958,102.524891,10.000000,50.000000,60.000000,100.000000,1080.000000
lights,19735.0,3.801875,7.935988,0.000000,0.000000,0.000000,0.000000,70.000000
T1,19735.0,21.686571,1.606066,16.790000,20.760000,21.600000,22.600000,26.260000
RH_1,19735.0,40.259739,3.979299,27.023333,37.333333,39.656667,43.066667,63.360000
T2,19735.0,20.341219,2.192974,16.100000,18.790000,20.000000,21.500000,29.856667
RH_2,19735.0,40.420420,4.069813,20.463333,37.900000,40.500000,43.260000,56.026667
T3,19735.0,22.267611,2.006111,17.200000,20.790000,22.100000,23.290000,29.236000
RH_3,19735.0,39.242500,3.254576,28.766667,36.900000,38.530000,41.760000,50.163333
T4,19735.0,20.855335,2.042884,15.100000,19.530000,20.666667,22.100000,26.200000
RH_4,19735.0,39.026904,4.341321,27.660000,35.530000,38.400000,42.156667,51.090000
T5,19735.0,19.592106,1.844623,15.330000,18.277500,19.390000,20.619643,25.795000
RH_5,19735.0,50.949283,9.022034,29.815000,45.400000,49.090000,53.663333,96.321667
T6,19735.0,7.910939,6.090347,-6.065000,3.626667,7.300000,11.256000,28.290000
RH_6,19735.0,54.609083,31.149806,1.000000,30.025000,55.290000,83.226667,99.900000
T7,19735.0,20.267106,2.109993,15.390000,18.700000,20.033333,21.600000,26.000000
RH_7,19735.0,35.388200,5.114208,23.200000,31.500000,34.863333,39.000000,51.400000
T8,19735.0,22.029107,1.956162,16.306667,20.790000,22.100000,23.390000,27.230000
RH_8,19735.0,42.936165,5.224361,29.600000,39.066667,42.375000,46.536000,58.780000
T9,19735.0,19.485828,2.014712,14.890000,18.000000,19.390000,20.600000,24.500000
RH_9,19735.0,41.552401,4.151497,29.166667,38.500000,40.900000,44.338095,53.326667
T_out,19735.0,7.411665,5.317409,-5.000000,3.666667,6.916667,10.408333,26.100000
Press_mm_hg,19735.0,755.522602,7.399441,729.300000,750.933333,756.100000,760.933333,772.300000
RH_out,19735.0,79.750418,14.901088,24.000000,70.333333,83.666667,91.666667,100.000000
Windspeed,19735.0,4.039752,2.451221,0.000000,2.000000,3.666667,5.500000,14.000000
Visibility,19735.0,38.330834,11.794719,1.000000,29.000000,40.000000,40.000000,66.000000
Tdewpoint,19735.0,3.760707,4.194648,-6.600000,0.900000,3.433333,6.566667,15.500000
rv1,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
rv2,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530

In [20]:
# Remove the unwanted columns
df = df.drop(columns=["date", "lights"])

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["Appliances"]), df["Appliances"], test_size=0.3, random_state=42)

# Normalize the train and test sets
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
from sklearn.metrics import mean_absolute_error

In [34]:
model = LinearRegression()

model.fit(X_train_scaled, y_train)

prediction = model.predict(X_train_scaled)

mae = mean_absolute_error(prediction, y_train)

In [30]:
#question 18
print(mae.round(3))

53.742

In [28]:
#question 19
from sklearn.metrics import mean_squared_error

# Calculate the RMSE
rmse = mean_squared_error(prediction, y_train, squared=False)
print(rmse.round(3))

95.216

In [44]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(X_train_scaled, y_train)

pred = ridge_reg.predict(X_train_scaled)

rmse = mean_squared_error(pred, y_train, squared=False)

In [46]:
print(rmse.round(3))

95.23

In [ ]:
#Question 23
# Yes
#from the above code it can be seen that there was a change